"""Block agent edits to basicly-generated files (Claude Code PreToolUse hook).

Wired into ``.claude/settings.json`` by ``basicly hooks-build`` for the
Edit/Write tool family. Every file basicly projects carries a ``Generated by
... basicly ...`` marker in its opening lines; hand-editing one is always wrong
because the next build silently overwrites it — the fix belongs in the catalog
source. Git hooks cannot catch this before the damage is done; this guard
blocks at tool time (exit code 2 tells Claude Code to refuse the call and show
stderr to the model).

The guard fails open by design: malformed payloads, unreadable files, or
missing paths exit 0 so a hook bug can never lock an agent out of normal edits.
It is a guardrail against accidents, not a security boundary.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

# Both marker flavors ("Generated by basicly vX" on fragment projections,
# "Generated by `basicly skills-build`" on projected skills) contain these two
# substrings on one line within the opening lines of the file.
MARKER_TERMS = ("Generated by", "basicly")
MARKER_SEARCH_LINES = 10

# The projection manifest is JSON and cannot carry a comment marker; it is
# matched by its constant basename instead (its directory is configurable).
MANIFEST_BASENAME = "generated-manifest.json"

BLOCK_EXIT_CODE = 2


def is_generated(path: Path) -> bool:
    """Return True when *path* is a basicly-generated file (marker or manifest)."""
    if path.name == MANIFEST_BASENAME:
        return True
    try:
        with path.open("r", encoding="utf-8", errors="ignore") as handle:
            for _ in range(MARKER_SEARCH_LINES):
                line = handle.readline()
                if not line:
                    break
                if all(term in line for term in MARKER_TERMS):
                    return True
    except OSError:
        return False
    return False


def target_path(payload: dict) -> Path | None:
    """Extract the file path an Edit/Write-family tool call is about to touch."""
    tool_input = payload.get("tool_input")
    if not isinstance(tool_input, dict):
        return None
    raw = tool_input.get("file_path") or tool_input.get("notebook_path")
    if not isinstance(raw, str) or not raw.strip():
        return None
    return Path(raw)


def main() -> int:
    """Entry point: read the PreToolUse payload from stdin and allow or block."""
    try:
        payload = json.load(sys.stdin)
    except json.JSONDecodeError, UnicodeDecodeError:
        return 0
    if not isinstance(payload, dict):
        return 0

    path = target_path(payload)
    if path is None or not path.is_file():
        return 0

    if is_generated(path):
        print(
            f"BLOCKED: {path} is generated by basicly and will be overwritten on the "
            "next build. Edit the catalog source instead (fragment/skill/agent YAML "
            "under .basicly/core or the .basicly-local overlay), then run "
            "`basicly build` / `basicly skills-build` / `basicly agents-build` to "
            "regenerate it.",
            file=sys.stderr,
        )
        return BLOCK_EXIT_CODE
    return 0


if __name__ == "__main__":
    sys.exit(main())
