from __future__ import annotations

import json
import sys
from pathlib import Path

MARKER_TERMS = ("Generated by", "basicly")
MARKER_SEARCH_LINES = 10

MANIFEST_BASENAME = "generated-manifest.json"

BLOCK_EXIT_CODE = 2


def is_generated(path: Path) -> bool:
    if path.name == MANIFEST_BASENAME:
        return True
    try:
        with path.open("r", encoding="utf-8", errors="ignore") as handle:
            for _ in range(MARKER_SEARCH_LINES):
                line = handle.readline()
                if not line:
                    break
                if all(term in line for term in MARKER_TERMS):
                    return True
    except OSError:
        return False
    return False


def target_path(payload: dict) -> Path | None:
    tool_input = payload.get("tool_input")
    if not isinstance(tool_input, dict):
        return None
    raw = tool_input.get("file_path") or tool_input.get("notebook_path")
    if not isinstance(raw, str) or not raw.strip():
        return None
    return Path(raw)


def main() -> int:
    try:
        payload = json.load(sys.stdin)
    except json.JSONDecodeError, UnicodeDecodeError:
        return 0
    if not isinstance(payload, dict):
        return 0

    path = target_path(payload)
    if path is None or not path.is_file():
        return 0

    if is_generated(path):
        print(
            f"BLOCKED: {path} is generated by basicly and will be overwritten on the "
            "next build. Edit the catalog source instead (fragment/skill/agent YAML "
            "under .basicly/core or the .basicly-local overlay), then run "
            "`basicly build` / `basicly skills-build` / `basicly agents-build` to "
            "regenerate it.",
            file=sys.stderr,
        )
        return BLOCK_EXIT_CODE
    return 0


if __name__ == "__main__":
    sys.exit(main())
