-- WezTerm configuration for long-running coding sessions.
-- Inspired by https://github.com/josean-dev/dev-environment-files
-- This file is generated by terminal-setup; edit the template in the repo.

local wezterm = require("wezterm")
local config = wezterm.config_builder and wezterm.config_builder() or {}
local act = wezterm.action
local is_windows = wezterm.target_triple:find("windows") ~= nil
local home_dir = wezterm.home_dir
local is_wsl = os.getenv("WSL_DISTRO_NAME") ~= nil or os.getenv("WSL_INTEROP") ~= nil
local wsl_default_domain = nil
-- Windows-native profiles must name the local domain explicitly. A SpawnCommand
-- with no `domain` field falls back to CurrentPaneDomain, and the default tab on
-- Windows is the WSL domain, so the launcher would start these inside WSL: Git
-- Bash dies immediately because its Windows path is not in the WSL filesystem
-- namespace, while pwsh and cmd only limp along through WSL interop, in a WSL
-- pane with WSL cwd semantics.
local local_domain = { DomainName = "local" }
local wsl_startup_args = {
  "zsh",
  "-lc",
  'cd "__WSL_START_DIR__" 2>/dev/null || cd "$HOME"; exec zsh -l',
}

local function basename(path)
  if not path or path == "" then
    return ""
  end
  return path:gsub("^.*[\\/]", "")
end

local function pane_cwd_basename(pane)
  local cwd_uri = pane and pane:get_current_working_dir() or nil
  if not cwd_uri then
    return ""
  end
  local cwd_path = cwd_uri.file_path or tostring(cwd_uri)
  return basename(cwd_path)
end

-- Default to WSL Ubuntu on Windows, otherwise the native shell.
if is_windows then
  local function pick_wsl_domain()
    local ok, domains = pcall(function()
      return wezterm.default_wsl_domains()
    end)
    if not ok or type(domains) ~= "table" then
      return nil
    end
    config.wsl_domains = domains

    local preferred = {
      "WSL:Ubuntu-24.04",
      "WSL:Ubuntu",
    }
    for _, candidate in ipairs(preferred) do
      for _, domain in ipairs(domains) do
        if domain.name == candidate then
          return candidate
        end
      end
    end

    for _, domain in ipairs(domains) do
      local name = domain.name
      if type(name) == "string" and name:lower():find("wsl:ubuntu", 1, true) then
        return name
      end
    end

    if #domains > 0 and type(domains[1].name) == "string" then
      return domains[1].name
    end
    return nil
  end

  wsl_default_domain = pick_wsl_domain()
  if wsl_default_domain then
    config.default_domain = wsl_default_domain
    -- Keep the WSL startup args on the WSL domain entry only. A global
    -- config.default_prog applies to the local domain too, so on Windows it
    -- makes `wezterm cli spawn --domain-name local` (no explicit program) try
    -- to run `zsh -lc ...` on the Windows side: the spawn still returns a pane
    -- id and exit 0, but the shell dies immediately with "didn't exit cleanly"
    -- and the pane reports an empty cwd.
    for _, domain in ipairs(config.wsl_domains or {}) do
      if domain.name == wsl_default_domain then
        domain.default_prog = wsl_startup_args
        domain.default_cwd = home_dir
      end
    end
  end
end

config.default_cwd = home_dir

-- Launcher profiles for fast context switches between WSL and Windows shells.
config.launch_menu = {}
if is_windows then
  if wsl_default_domain then
    table.insert(config.launch_menu, {
      label = "Ubuntu (WSL)",
      domain = { DomainName = wsl_default_domain },
      args = wsl_startup_args,
    })
  end
  table.insert(config.launch_menu, {
    label = "PowerShell",
    domain = local_domain,
    args = { "pwsh.exe", "-NoLogo" },
  })
  -- Offer Git Bash when Git for Windows is installed. Probe the standard
  -- system and per-user locations; skip C:\Windows\System32\bash.exe, which is
  -- the WSL launcher, not Git Bash. Launch as a login+interactive shell so the
  -- rc files (and the starship prompt wired in by terminal-setup) load.
  local function find_git_bash()
    local candidates = {
      "C:\\Program Files\\Git\\bin\\bash.exe",
      "C:\\Program Files (x86)\\Git\\bin\\bash.exe",
    }
    local localappdata = os.getenv("LOCALAPPDATA")
    if localappdata then
      table.insert(candidates, localappdata .. "\\Programs\\Git\\bin\\bash.exe")
    end
    for _, candidate in ipairs(candidates) do
      local handle = io.open(candidate, "r")
      if handle then
        handle:close()
        return candidate
      end
    end
    return nil
  end
  local git_bash = find_git_bash()
  if git_bash then
    table.insert(config.launch_menu, {
      label = "Git Bash",
      domain = local_domain,
      args = { git_bash, "--login", "-i" },
    })
  end
  table.insert(config.launch_menu, {
    label = "Command Prompt",
    domain = local_domain,
    args = { "cmd.exe" },
  })
else
  table.insert(config.launch_menu, {
    label = "zsh",
    args = { "zsh", "-l" },
  })
  table.insert(config.launch_menu, {
    label = "bash",
    args = { "bash", "-l" },
  })
end

-- Performance and stability defaults.
config.scrollback_lines = 10000
config.max_fps = 30
config.animation_fps = 10
config.cursor_blink_rate = 0
config.enable_scroll_bar = true
config.check_for_updates = false
config.window_close_confirmation = "NeverPrompt"
config.adjust_window_size_when_changing_font_size = false

-- Display stability: prefer X11 over Wayland.
-- Windows and WSL use software rendering to bypass GPU driver rendering paths.
-- Limit redraws above to keep CPU use bounded during long coding sessions.
config.enable_wayland = false
config.front_end = (is_windows or is_wsl) and "Software" or "WebGpu"

-- Always use the dark color scheme; do not query the desktop environment
-- for the system theme. This avoids xdg-desktop-portal warnings under WSLg
-- and keeps the appearance consistent across Windows, WSL, and Linux.
config.color_scheme = "Tokyo Night"
config.window_background_opacity = 1.0
config.skip_close_confirmation_for_processes_named = {
  "bash",
  "bash.exe",
  "zsh",
  "tmux",
  "pwsh.exe",
  "powershell.exe",
  "cmd.exe",
}

-- Deep navy background with readable text and distinct terminal colors.
config.colors = {
  foreground = "#D2DAE5",
  background = "#101B2A",
  cursor_bg = "#89B4FA",
  cursor_border = "#89B4FA",
  cursor_fg = "#101B2A",
  selection_bg = "#29476B",
  selection_fg = "#DEE6F0",
  split = "#314A6B",
  ansi = { "#1E2D45", "#F38BA8", "#A6E3A1", "#F9E2AF", "#89B4FA", "#CBA6F7", "#94E2D5", "#CAD3DF" },
  brights = { "#B7C5DA", "#FFAAC2", "#C0F0B8", "#FFF0C2", "#B4D0FF", "#DEC2FF", "#B4F0E5", "#DEE6F0" },
  tab_bar = {
    background = "#060D18",
    active_tab = { bg_color = "#1D3557", fg_color = "#DEE6F0", intensity = "Bold" },
    inactive_tab = { bg_color = "#101D30", fg_color = "#A9BCD5" },
    inactive_tab_hover = { bg_color = "#243F60", fg_color = "#DEE6F0" },
    new_tab = { bg_color = "#101D30", fg_color = "#A9BCD5" },
    new_tab_hover = { bg_color = "#243F60", fg_color = "#DEE6F0" },
  },
}
-- Soften application-selected colors as well as the ANSI palette.
config.foreground_text_hsb = { hue = 1.0, saturation = 1.0, brightness = 0.92 }
config.window_frame = {
  active_titlebar_bg = "#060D18",
  inactive_titlebar_bg = "#060D18",
  active_titlebar_fg = "#DCE6F5",
  inactive_titlebar_fg = "#A9BCD5",
}

-- Every font named here must resolve on a fresh machine, or WezTerm raises a
-- "Unable to load a font specified in your font config" notification at
-- startup. WezTerm bundles JetBrains Mono, Noto Color Emoji, and Symbols Nerd
-- Font Mono, so Nerd Font glyphs (starship, statusline) render without
-- installing any extra fonts.
if is_windows then
  config.font = wezterm.font_with_fallback({
    { family = "Cascadia Mono", weight = "Regular" },
    "JetBrains Mono",
    "Consolas",
    "Noto Color Emoji",
  })
else
  config.font = wezterm.font_with_fallback({
    "DejaVu Sans Mono",
    "JetBrains Mono",
    "Noto Color Emoji",
  })
end
config.font_size = 12.0
if is_windows then
  -- Use solid regular strokes and a readable gray for ANSI dim text.
  config.font_rules = {
    {
      intensity = "Half",
      font = wezterm.font_with_fallback(
        { "Cascadia Mono", "JetBrains Mono", "Noto Color Emoji" },
        { weight = "Regular", foreground = "#C4CEDC" }
      ),
    },
  }
end
-- Preserve literal characters when reading commands, code and diffs.
config.harfbuzz_features = { "calt=0", "clig=0", "liga=0" }
config.line_height = 1.2
if is_windows then
  -- Grayscale smoothing avoids LCD color fringes on scaled displays.
  config.freetype_load_target = "Normal"
  config.freetype_render_target = "Normal"
end
config.initial_cols = 120
config.initial_rows = 30

-- Window appearance.
config.enable_tab_bar = true
config.hide_tab_bar_if_only_one_tab = false
config.use_fancy_tab_bar = true
config.tab_bar_at_bottom = false
config.window_decorations = "TITLE | RESIZE"
config.status_update_interval = 3000

local new_tab_action = act.SpawnTab("DefaultDomain")
if is_windows and wsl_default_domain then
  new_tab_action = act.SpawnCommandInNewTab({
    domain = { DomainName = wsl_default_domain },
    cwd = home_dir,
    args = wsl_startup_args,
  })
end

local workspace_launcher_action = act.ShowLauncherArgs({ flags = "FUZZY|WORKSPACES" })
local rename_tab_action = act.PromptInputLine({
  description = "Rename tab",
  action = wezterm.action_callback(function(window, _, line)
    if line and line ~= "" then
      window:active_tab():set_title(line)
    end
  end),
})

local open_config_action
if is_windows then
  open_config_action = act.SpawnCommandInNewTab({
    domain = local_domain,
    args = { "notepad.exe", wezterm.config_file },
  })
else
  local open_config_command = {
    args = { "zsh", "-lc", '${EDITOR:-nano} "' .. wezterm.config_file .. '"' },
  }
  open_config_action = act.SpawnCommandInNewTab(open_config_command)
end

wezterm.on("format-tab-title", function(tab, _, _, _, _, max_width)
  local pane = tab.active_pane
  local cwd = ""
  if pane and pane.current_working_dir then
    local cwd_path = pane.current_working_dir.file_path or tostring(pane.current_working_dir)
    cwd = basename(cwd_path)
  end

  local title = tab.tab_title
  if not title or title == "" then
    title = cwd ~= "" and cwd or (pane and pane.title or "shell")
  end
  return wezterm.truncate_right(" " .. title .. " ", max_width)
end)

wezterm.on("update-right-status", function(window, pane)
  local workspace = window:active_workspace()
  local cwd = pane_cwd_basename(pane)
  local cwd_text = cwd ~= "" and cwd or "~"
  window:set_right_status(wezterm.format({
    { Foreground = { Color = "#91A4BF" } },
    { Text = " " .. workspace .. " " },
    { Foreground = { Color = "#89B4FA" } },
    { Text = cwd_text .. " " },
  }))
end)

-- Mouse selection behavior: selecting text with the left mouse button copies it
-- to the clipboard on release (Windows Terminal style). Right-click pastes the
-- clipboard. Middle-click pastes the primary selection on all platforms.
config.mouse_bindings = {
  {
    event = { Down = { streak = 1, button = "Right" } },
    mods = "NONE",
    action = act.PasteFrom("Clipboard"),
  },
  {
    event = { Down = { streak = 1, button = "Middle" } },
    mods = "NONE",
    action = act.PasteFrom("PrimarySelection"),
  },
}

-- Copy to clipboard when the selection is completed with the mouse.
config.selection_word_boundary = " \t\n{}[]()\"'"
config.mouse_bindings = config.mouse_bindings or {}
table.insert(config.mouse_bindings, {
  event = { Up = { streak = 1, button = "Left" } },
  mods = "NONE",
  action = act.CompleteSelectionOrOpenLinkAtMouseCursor("ClipboardAndPrimarySelection"),
})

-- Key bindings. The leader is Ctrl+Shift+Space: plain Ctrl+Space is the tmux
-- prefix (deployed tmux.conf), so the leader must not shadow it, and readline
-- shortcuts such as Ctrl+A/Ctrl+E stay untouched. Ctrl+Shift+Space is free on
-- Windows and Linux (unlike Alt+Space, which opens the Windows system menu).
config.leader = { key = "Space", mods = "CTRL|SHIFT", timeout_milliseconds = 3000 }
config.keys = {
  { key = "t", mods = "CTRL|SHIFT", action = new_tab_action },
  { key = "w", mods = "CTRL|SHIFT", action = act.CloseCurrentTab({ confirm = false }) },
  { key = "c", mods = "CTRL", action = act.SendKey({ key = "c", mods = "CTRL" }) },
  { key = "c", mods = "CTRL|SHIFT", action = act.CopyTo("ClipboardAndPrimarySelection") },
  { key = "v", mods = "CTRL|SHIFT", action = act.PasteFrom("Clipboard") },
  { key = "f", mods = "CTRL|SHIFT", action = act.Search("CurrentSelectionOrEmptyString") },
  -- Jump between prompts in the scrollback (needs the OSC 133 marks emitted
  -- by the deployed zshrc) — fast navigation through long command output.
  { key = "UpArrow", mods = "CTRL|SHIFT", action = act.ScrollToPrompt(-1) },
  { key = "DownArrow", mods = "CTRL|SHIFT", action = act.ScrollToPrompt(1) },
  { key = "p", mods = "CTRL|SHIFT", action = act.QuickSelect },
  { key = "l", mods = "CTRL|SHIFT", action = act.ShowLauncher },
  { key = "=", mods = "CTRL|SHIFT", action = act.IncreaseFontSize },
  { key = "-", mods = "CTRL|SHIFT", action = act.DecreaseFontSize },
  { key = "0", mods = "CTRL", action = act.ResetFontSize },
  { key = "Enter", mods = "ALT", action = act.ToggleFullScreen },
  { key = "c", mods = "LEADER", action = new_tab_action },
  { key = "w", mods = "LEADER", action = workspace_launcher_action },
  { key = ",", mods = "LEADER", action = rename_tab_action },
  { key = ".", mods = "LEADER", action = open_config_action },
  { key = "x", mods = "LEADER", action = act.CloseCurrentPane({ confirm = false }) },
  { key = "x", mods = "CTRL|ALT", action = act.CloseCurrentPane({ confirm = false }) },
  { key = "\\", mods = "LEADER", action = act.SplitHorizontal({ domain = "CurrentPaneDomain" }) },
  { key = "\\", mods = "CTRL|ALT", action = act.SplitHorizontal({ domain = "CurrentPaneDomain" }) },
  { key = "phys:Backslash", mods = "CTRL|ALT", action = act.SplitHorizontal({ domain = "CurrentPaneDomain" }) },
  { key = "phys:Backslash", mods = "LEADER", action = act.SplitHorizontal({ domain = "CurrentPaneDomain" }) },
  { key = "v", mods = "LEADER", action = act.SplitHorizontal({ domain = "CurrentPaneDomain" }) },
  { key = "s", mods = "LEADER", action = act.SplitVertical({ domain = "CurrentPaneDomain" }) },
  { key = "|", mods = "LEADER", action = act.SplitHorizontal({ domain = "CurrentPaneDomain" }) },
  { key = "-", mods = "LEADER", action = act.SplitVertical({ domain = "CurrentPaneDomain" }) },
  { key = "-", mods = "CTRL|ALT", action = act.SplitVertical({ domain = "CurrentPaneDomain" }) },
  { key = "h", mods = "LEADER", action = act.ActivatePaneDirection("Left") },
  { key = "j", mods = "LEADER", action = act.ActivatePaneDirection("Down") },
  { key = "k", mods = "LEADER", action = act.ActivatePaneDirection("Up") },
  { key = "l", mods = "LEADER", action = act.ActivatePaneDirection("Right") },
  { key = "z", mods = "LEADER", action = act.TogglePaneZoomState },
}

return config
