-- WezTerm configuration for long-running coding sessions.
-- Inspired by https://github.com/josean-dev/dev-environment-files
-- This file is generated by terminal-setup; edit the template in the repo.

local wezterm = require("wezterm")
local config = wezterm.config_builder and wezterm.config_builder() or {}
local is_windows = wezterm.target_triple:find("windows") ~= nil
local home_dir = wezterm.home_dir
local is_wsl = os.getenv("WSL_DISTRO_NAME") ~= nil or os.getenv("WSL_INTEROP") ~= nil
local wsl_default_domain = nil
local wsl_startup_args = {
  "zsh",
  "-lc",
  'cd "__WSL_START_DIR__" 2>/dev/null || cd "$HOME"; exec zsh -l',
}

-- Default to WSL Ubuntu on Windows, otherwise the native shell.
if is_windows then
  local function pick_wsl_domain()
    local ok, domains = pcall(function()
      return wezterm.default_wsl_domains()
    end)
    if not ok or type(domains) ~= "table" then
      return nil
    end
    config.wsl_domains = domains

    local preferred = {
      "WSL:Ubuntu-24.04",
      "WSL:Ubuntu",
    }
    for _, candidate in ipairs(preferred) do
      for _, domain in ipairs(domains) do
        if domain.name == candidate then
          return candidate
        end
      end
    end

    for _, domain in ipairs(domains) do
      local name = domain.name
      if type(name) == "string" and name:lower():find("wsl:ubuntu", 1, true) then
        return name
      end
    end

    if #domains > 0 and type(domains[1].name) == "string" then
      return domains[1].name
    end
    return nil
  end

  wsl_default_domain = pick_wsl_domain()
  if wsl_default_domain then
    config.default_domain = wsl_default_domain
    config.default_prog = wsl_startup_args
    for _, domain in ipairs(config.wsl_domains or {}) do
      if domain.name == wsl_default_domain then
        domain.default_prog = wsl_startup_args
        domain.default_cwd = home_dir
      end
    end
  end
end

if not (is_windows and wsl_default_domain) then
  config.default_prog = nil
end
config.default_cwd = home_dir

-- Performance and stability defaults.
config.scrollback_lines = 100000
config.enable_scroll_bar = true
config.check_for_updates = false
config.window_close_confirmation = "NeverPrompt"
config.adjust_window_size_when_changing_font_size = false

-- WSL / cross-platform display stability: prefer X11 over Wayland. When
-- running inside WSL use software rendering to avoid MESA/ZINK/DRI warnings
-- caused by incomplete GPU drivers in WSLg; native hosts keep WebGPU.
config.enable_wayland = false
config.front_end = is_wsl and "Software" or "WebGpu"

-- Always use the dark color scheme; do not query the desktop environment
-- for the system theme. This avoids xdg-desktop-portal warnings under WSLg
-- and keeps the appearance consistent across Windows, WSL, and Linux.
config.color_scheme = "Tokyo Night"
config.window_background_opacity = 1.0
config.skip_close_confirmation_for_processes_named = {
  "bash",
  "zsh",
  "tmux",
  "pwsh.exe",
  "powershell.exe",
  "cmd.exe",
}

-- Color scheme (tokyonight night inspired by josean-dev).
config.colors = {
  foreground = "#CBE0F0",
  background = "#011423",
  cursor_bg = "#47FF9C",
  cursor_border = "#47FF9C",
  cursor_fg = "#011423",
  selection_bg = "#033259",
  selection_fg = "#CBE0F0",
  ansi = { "#214969", "#E52E2E", "#44FFB1", "#FFE073", "#0FC5ED", "#a277ff", "#24EAF7", "#24EAF7" },
  brights = { "#214969", "#E52E2E", "#44FFB1", "#FFE073", "#A277FF", "#a277ff", "#24EAF7", "#24EAF7" },
}

-- Put broadly available fonts first to avoid startup warnings on fresh machines.
if is_windows then
  config.font = wezterm.font_with_fallback({
    "Consolas",
    "Cascadia Mono",
    "MesloLGS Nerd Font Mono",
    "Noto Color Emoji",
  })
else
  config.font = wezterm.font_with_fallback({
    "DejaVu Sans Mono",
    "Noto Sans Mono",
    "MesloLGS Nerd Font Mono",
    "JetBrains Mono",
    "Noto Color Emoji",
  })
end
config.font_size = 13.0
config.initial_cols = 120
config.initial_rows = 30

-- Window appearance.
config.enable_tab_bar = true
config.hide_tab_bar_if_only_one_tab = false
config.use_fancy_tab_bar = true
config.tab_bar_at_bottom = false
config.window_decorations = "TITLE | RESIZE"

local new_tab_action = wezterm.action.SpawnTab("DefaultDomain")
if is_windows and wsl_default_domain then
  new_tab_action = wezterm.action.SpawnCommandInNewTab({
    domain = { DomainName = wsl_default_domain },
    cwd = home_dir,
    args = wsl_startup_args,
  })
end

-- Mouse selection behavior: selecting text with the left mouse button copies it
-- to the clipboard on release (Windows Terminal style). Right-click pastes the
-- clipboard. Middle-click pastes the primary selection on all platforms.
config.mouse_bindings = {
  {
    event = { Down = { streak = 1, button = "Right" } },
    mods = "NONE",
    action = wezterm.action.PasteFrom("Clipboard"),
  },
  {
    event = { Down = { streak = 1, button = "Middle" } },
    mods = "NONE",
    action = wezterm.action.PasteFrom("PrimarySelection"),
  },
}

-- Copy to clipboard when the selection is completed with the mouse.
config.selection_word_boundary = " \t\n{}[]()\"'"
config.mouse_bindings = config.mouse_bindings or {}
table.insert(config.mouse_bindings, {
  event = { Up = { streak = 1, button = "Left" } },
  mods = "NONE",
  action = wezterm.action.CompleteSelectionOrOpenLinkAtMouseCursor("ClipboardAndPrimarySelection"),
})

-- Key bindings. Use Ctrl+Space as the leader so standard readline shortcuts
-- such as Ctrl+A (beginning-of-line) and Ctrl+E (end-of-line) keep working in
-- the shell. Ctrl+Space has no default binding in WezTerm, zsh, tmux, or most
-- terminal editors, so it avoids the conflict caused by Ctrl+A.
config.leader = { key = "Space", mods = "CTRL", timeout_milliseconds = 3000 }
config.keys = {
  { key = "t", mods = "CTRL|SHIFT", action = new_tab_action },
  { key = "w", mods = "CTRL|SHIFT", action = wezterm.action.CloseCurrentTab({ confirm = false }) },
  { key = "c", mods = "CTRL", action = wezterm.action.SendKey({ key = "c", mods = "CTRL" }) },
  { key = "c", mods = "CTRL|SHIFT", action = wezterm.action.CopyTo("ClipboardAndPrimarySelection") },
  { key = "v", mods = "CTRL|SHIFT", action = wezterm.action.PasteFrom("Clipboard") },
  { key = "q", mods = "CTRL|SHIFT", action = wezterm.action.QuitApplication },
  { key = "=", mods = "CTRL|SHIFT", action = wezterm.action.IncreaseFontSize },
  { key = "-", mods = "CTRL|SHIFT", action = wezterm.action.DecreaseFontSize },
  { key = "0", mods = "CTRL", action = wezterm.action.ResetFontSize },
  { key = "Enter", mods = "ALT", action = wezterm.action.ToggleFullScreen },
  { key = "c", mods = "LEADER", action = new_tab_action },
  { key = "x", mods = "LEADER", action = wezterm.action.CloseCurrentPane({ confirm = false }) },
  { key = "x", mods = "CTRL|ALT", action = wezterm.action.CloseCurrentPane({ confirm = false }) },
  { key = "\\", mods = "LEADER", action = wezterm.action.SplitHorizontal({ domain = "CurrentPaneDomain" }) },
  { key = "\\", mods = "CTRL|ALT", action = wezterm.action.SplitHorizontal({ domain = "CurrentPaneDomain" }) },
  { key = "phys:Backslash", mods = "CTRL|ALT", action = wezterm.action.SplitHorizontal({ domain = "CurrentPaneDomain" }) },
  { key = "phys:Backslash", mods = "LEADER", action = wezterm.action.SplitHorizontal({ domain = "CurrentPaneDomain" }) },
  { key = "v", mods = "LEADER", action = wezterm.action.SplitHorizontal({ domain = "CurrentPaneDomain" }) },
  { key = "s", mods = "LEADER", action = wezterm.action.SplitVertical({ domain = "CurrentPaneDomain" }) },
  { key = "|", mods = "LEADER", action = wezterm.action.SplitHorizontal({ domain = "CurrentPaneDomain" }) },
  { key = "-", mods = "LEADER", action = wezterm.action.SplitVertical({ domain = "CurrentPaneDomain" }) },
  { key = "-", mods = "CTRL|ALT", action = wezterm.action.SplitVertical({ domain = "CurrentPaneDomain" }) },
  { key = "h", mods = "LEADER", action = wezterm.action.ActivatePaneDirection("Left") },
  { key = "j", mods = "LEADER", action = wezterm.action.ActivatePaneDirection("Down") },
  { key = "k", mods = "LEADER", action = wezterm.action.ActivatePaneDirection("Up") },
  { key = "l", mods = "LEADER", action = wezterm.action.ActivatePaneDirection("Right") },
  { key = "z", mods = "LEADER", action = wezterm.action.TogglePaneZoomState },
}

return config
