"""Tests for target renderers."""

from __future__ import annotations

from pathlib import Path

from basicly import __version__
from basicly.loader import load_fragments, load_targets
from basicly.planner import plan_outputs
from basicly.renderers.claude import render as render_claude
from basicly.renderers.common import sha256_of_text
from basicly.renderers.copilot import render as render_copilot

REPO_ROOT = Path(__file__).parent.parent.parent


def test_agents_md_contains_header() -> None:
    """The generated AGENTS.md contains the generated header and expected sections."""
    targets = load_targets(REPO_ROOT / ".basicly" / "targets")
    target_names = {t.name for t in targets}
    fragments = load_fragments(REPO_ROOT / ".basicly" / "fragments", target_names)
    planned = plan_outputs(fragments, targets, REPO_ROOT)
    agents = next(p for p in planned if p.output_path == REPO_ROOT / "AGENTS.md")
    content = render_claude(agents, REPO_ROOT / ".basicly" / "templates", __version__)

    assert "<!-- Generated by basicly" in content
    assert "## Agent Baseline" not in content
    assert "## Project Defaults" in content


def test_copilot_instruction_front_matter() -> None:
    """Scoped Copilot instructions include applyTo front matter."""
    targets = load_targets(REPO_ROOT / ".basicly" / "targets")
    target_names = {t.name for t in targets}
    fragments = load_fragments(REPO_ROOT / ".basicly" / "fragments", target_names)
    planned = plan_outputs(fragments, targets, REPO_ROOT)
    scoped = next(p for p in planned if str(p.output_path).endswith("python-style.instructions.md"))
    content = render_copilot(scoped, REPO_ROOT / ".basicly" / "templates", __version__)

    assert "applyTo:" in content
    assert '"**/*.py"' in content


def test_sha256_of_text() -> None:
    """sha256_of_text returns a stable, prefixed hash."""
    assert sha256_of_text("hello").startswith("sha256:")
    assert sha256_of_text("hello") == sha256_of_text("hello")
    assert sha256_of_text("hello") != sha256_of_text("world")
