from __future__ import annotations

import re

_PATTERNS = (
    r"noqa\b",
    r"nosec\b",
    r"nolint\b",
    r"nosonar\b",
    r"type:\s*ignore",
    r"pragma:",
    r"pylint:",
    r"flake8:",
    r"mypy:",
    r"pyright:",
    r"ruff:",
    r"bandit:",
    r"vulture:",
    r"isort:",
    r"nopycln",
    r"fmt:\s*(?:on|off|skip)",
    r"yapf:\s*(?:disable|enable)",
    r"coding[:=]",
    r"-\*-",
    r"[a-z][a-z0-9-]*-waiver:",
    r"shellcheck\b",
    r"eslint-disable",
    r"eslint-enable",
    r"eslint-env",
    r"globals\b",
    r"prettier-ignore",
    r"biome-ignore",
    r"oxlint-disable",
    r"stylelint-disable",
    r"stylelint-enable",
    r"@ts-ignore",
    r"@ts-expect-error",
    r"@ts-nocheck",
    r"@jsx\b",
    r"@jsxImportSource",
    r"@flow\b",
    r"istanbul\s+ignore",
    r"[cv]8\s+ignore",
    r"webpack[A-Za-z]+:",
    r"sourceMappingURL=",
    r"sourceURL=",
    r"go:[a-z]+",
    r"CHECKSTYLE:",
    r"ReSharper\s+(?:disable|restore)",
    r"<auto-generated",
    r"SPDX-[A-Za-z-]+:",
    r"\[if\s",
    r"\[endif\]",
)

_DIRECTIVE = re.compile(
    r"^(?:{})".format("|".join(_PATTERNS)),
    re.IGNORECASE,
)

_OPENERS = ("#!", "#", "//", "/*", "<!--", "<#", "--", "'")


def body(text: str) -> str:
    stripped = text.strip()
    for opener in _OPENERS:
        if stripped.startswith(opener):
            return stripped[len(opener) :].strip()
    return stripped


def is_directive(text: str) -> bool:

    lead = text.lstrip()
    if lead.startswith(("#!", "/*!", "//!")):
        return True
    return bool(_DIRECTIVE.match(body(text)))
