"""Shared rendering helpers."""

from __future__ import annotations

import hashlib
from pathlib import Path

from jinja2 import Environment, FileSystemLoader

from ..schema import Fragment, PlannedOutput


def make_env(templates_dir: Path) -> Environment:
    """Create a Jinja2 environment for templates under templates_dir."""
    return Environment(
        loader=FileSystemLoader(str(templates_dir)),
        autoescape=False,  # nosec B701
        keep_trailing_newline=True,
    )


def generated_header(version: str, fragments: list[Fragment]) -> str:
    """Return the standard generated-file HTML comment header."""
    ids = ", ".join(f.id for f in fragments)
    return (
        f"<!-- Generated by basicly v{version}. Do not edit manually. -->\n"
        f"<!-- Source fragments: {ids} -->\n"
    )


def render_output(env: Environment, planned: PlannedOutput, version: str) -> str:
    """Render a planned output using its target template."""
    template = env.get_template(planned.template)
    content = template.render(
        fragments=planned.fragments,
        header=generated_header(version, planned.fragments),
        target_name=planned.target_name,
        output_name=planned.output_name,
    )
    return content.rstrip() + "\n"


def sha256_of_text(text: str) -> str:
    """Return a sha256:... hash of the given text."""
    return "sha256:" + hashlib.sha256(text.encode("utf-8")).hexdigest()
